### ISSUE TITLE
Bootstrap Tour in modal auto scroll not working.

### ISSUE THREAD

**Issue by lalji1051** [sorich87/bootstrap-tour#350] opened 2014-12-12 13:03 UTC
![2](https://cloud.githubusercontent.com/assets/10166158/5411942/6177816a-822d-11e4-97cf-2d7ad9e8f60f.png)

**Comment by prathyusha1491** [comment] 2015-04-13 18:42
Use 
$('#modal').animate({ scrollTop: $('#Element').offset().top }, 500);
at the element to scroll to that particular element. This worked for me.

**Comment by moreketaki** [comment] 2016-03-14 16:33
I am having the same problem. I have set autoscroll to true but my step fails to scroll to the element. I can see its trying but just gets stuck at the bottom of the page without the arrow(placement). This is a regular page and not a modal dialog. 

Here is how the function looks right now. It works perfectly fine on a big screen which makes me assume that the logic is right.
Can you please advise me what I should do in this case?
Thanks.


`function MySettingsTour() {
        var tour = new Tour({       
        container: 'body',
        autoscroll: true,
            steps: [
                {
                    element: "#startDefaultTour",
                    title: "Do you want to be emailed when your filing is filed or rejected?",
                    content: "Set your Email Notification Preference",
                    placement: 'bottom'
                },
                {
                    element: $('.CommunicationList'),
                    title: "Set your email preferences.",
                    content: "Select the checkbox beside each email notification option you want to apply. \n Make sure to click Save Preferences.",
                    palcement: 'right'
                }
            ],
            storage: false
        });
        tour.init();
        tour.start();
    }`

![tour issue](https://cloud.githubusercontent.com/assets/17831794/13751272/c820b38a-e9df-11e5-9416-2f7900d5a939.PNG)

**Comment by danvim** [comment] 2016-06-04 09:07
It seems that the plugin doesn't do inner element auto scroll. I think somebody should add this as a feature request.

**Comment by sorich87** [comment] 2016-08-06 22:06
Duplicate of #325

**Closed by sorich87** 2016-08-06 22:06 UTC
Labels: bug

**Comment by webexpert4rv** [comment] 2018-01-08 09:57
Hello All,
I wanna scroll inner element (table) but horizontally. Do you have any solution for it ?
