### ISSUE TITLE
Dropdown menu prolem

### ISSUE THREAD

**Issue by cobyl** [sorich87/bootstrap-tour#463] opened 2015-07-29 14:13 UTC
Problem with twitter bootstrap 2.3.1 and dropdown menu opening:

I open drop down menu using onShow method from boostraptour.addStep  but dialog is shown as orphan, not close to element.

+ (question) 
Can i preserve dropdown menu open status between steps? (twitter bootstrap 2.3.1)

**Comment by asharma-r7** [comment] 2015-08-12 17:40
+1

**Comment by sorich87** [comment] 2016-08-04 07:39
Duplicate of #276

**Closed by sorich87** 2016-08-04 07:39 UTC
