### ISSUE TITLE
How to change the position of the pop-up box ?

### ISSUE THREAD

**Issue by ypsce** [sorich87/bootstrap-tour#563] opened 2016-07-28 02:01 UTC
Hello, Pop-up box position is not correct , By modifying the'placement'parameter or not changing the position of the pop-up box, how to do?
The value of "placement" parameter is set to "top" when the "Tour" is initialized!
![0160729154941](https://cloud.githubusercontent.com/assets/5241523/17241568/fc1ab056-55a4-11e6-8415-9bd5ef4d5f43.png)

**Comment by ypsce** [comment] 2016-07-28 02:05
Add screenshots:
![_20160728095533](https://cloud.githubusercontent.com/assets/5241523/17198798/c407891e-54aa-11e6-832f-b3f786db1f9f.png)

**Comment by aslamkhan669** [comment] 2016-07-28 08:37
Set element placement value to top.
`tour.addStep({
  path: "",
  host: "",
  element: "",
  placement: "top",
  smartPlacement: true,....});`

**Comment by ypsce** [comment] 2016-07-29 07:54
The value of "placement" parameter is set to "top" when the "Tour" is initialized!
![0160729154941](https://cloud.githubusercontent.com/assets/5241523/17241452/5317f9fa-55a4-11e6-998a-57ac76b7a368.png)

**Comment by aslamkhan669** [comment] 2016-07-29 08:30
set the placement value inside steps array for each step.

**Comment by sorich87** [comment] 2016-08-04 07:20
Duplicate of #502.

**Closed by sorich87** 2016-08-04 07:20 UTC
