### ISSUE TITLE
Decaf anyone?

### ISSUE THREAD

**Issue by ducu** [sorich87/bootstrap-tour#483] opened 2015-10-18 05:48 UTC
Hi guys, is there a JavaScript only fork of Bootstrap Tour?
I would contribute to that, and probably others would as somebody else [mentioned](https://github.com/sorich87/bootstrap-tour/issues/428#issuecomment-113360434).

I'm working on some redirect (hash only) and backdrop issues and I will fix that in my local js copy, but CoffeeScript is too much of a downer for me so can't push that back to you.

Thanks anyways, cheers.

**Comment by btecu** [comment] 2015-10-20 15:57
Ducule, this project looks like it's not maintained anymore.
When I get a chance I'll probably switch to Shepherd or Intro.js. You may want to look into those.
http://github.hubspot.com/shepherd/docs/welcome/
https://usablica.github.io/intro.js/

**Comment by ducu** [comment] 2015-10-20 16:02
Hey @btecu thanks for the suggestions,
I've seen those but I prefer BootstrapTour for the looks. I managed to hack around the issues I had so I'm fine now, cheers.

**Comment by sorich87** [comment] 2015-10-20 16:10
@btecu it's still maintained. I'm just too busy to quickly respond to all issues.

@ducu that's something I've been thinking about, an ES6 version.

**Comment by ducu** [comment] 2015-10-20 16:17
@sorich87 That would be good, cheers

**Comment by lubosdz** [comment] 2015-11-05 12:51
@sorich87 
First of all, this is a great-by design & API library. Thanx a lot for it.

Unfortunately, the library still has some issues and they make it less usable.
It's not really necessary to respond to all comments and review all issues, but perhaps **reviewing and merging PRs** would help a lot to speed up fixing stuff. PRs are usually already fixed and tested, can be merged within a while.

For those interested in "decoffeeing" - just copy & paste file:
https://github.com/sorich87/bootstrap-tour/blob/master/src/coffee/bootstrap-tour.coffee
into section "Try Coffee Script" at http://coffeescript.org/ into left window.
Coffee script will be instantly automatically converted into valid javascript.

**Closed** 2016-02-03 12:28 UTC
