### ISSUE TITLE
Scrolling issue with Bootstrap tour 

### ISSUE THREAD

**Issue by moreketaki** [sorich87/bootstrap-tour#526] opened 2016-03-14 17:50 UTC
I have set autoscroll to true but my step fails to scroll to the element. I can see its trying but just gets stuck at the bottom of the page without the arrow(placement). This is a regular page and not a modal dialog.

Here is how the function looks right now. It works perfectly fine on a big screen which makes me assume that the logic is right. Also I tried the solution mentioned in #350  but then instead of scrolling that page at that step the page gets scrolled down at the first step itself.
Can you please advise me what I should do in this case?
Thanks.

`function MySettingsTour() { var tour = new Tour({ container: 'body', autoscroll: true, steps: [ { element: "#startDefaultTour", title: "Do you want to be emailed when your filing is filed or rejected?", content: "Set your Email Notification Preference", placement: 'bottom' }, { element: $('.CommunicationList'), title: "Set your email preferences.", content: "Select the checkbox beside each email notification option you want to apply. \n Make sure to click Save Preferences.", palcement: 'right' } ], storage: false }); tour.init(); tour.start(); }`

![tour issue](https://cloud.githubusercontent.com/assets/17831794/13751618/5aa11514-e9e1-11e5-937f-f6c254bee110.PNG)

**Comment by sorich87** [comment] 2016-08-04 06:55
Duplicate of #350.

**Closed by sorich87** 2016-08-04 06:55 UTC
