### ISSUE TITLE
Scroll into view only considers window

### ISSUE THREAD

**Issue by gkz** [sorich87/bootstrap-tour#386] opened 2015-03-12 22:22 UTC
`_scrollIntoView` only scrolls the window. If an element is within another scrolling element, it should scroll that.

ie. consider `$element.offsetParent()` as the container, and then use `$element.position().top` to calculate the offset, before scrolling the container.

I have come up with a workaround for my specific case, but will have to think about the fully general case.

**Comment by sorich87** [comment] 2016-08-06 22:03
Duplicate of #325

**Closed by sorich87** 2016-08-06 22:03 UTC
Labels: enhancement
